name: Main

on: push

env:
  NODE_VERSION: 16
  VERCEL_ORG_ID: team_e2WfHoRuw9BQVW7oYmMSKRJ6

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: aboutbits/github-actions-node/setup-and-install@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Lint
        run: npm run lint
        shell: bash
      - name: Typecheck
        run: npm run typecheck
        shell: bash

  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: aboutbits/github-actions-node/setup-and-install@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Test
        run: npm run test
        shell: bash

  deploy-main:
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true
    if: github.ref == 'refs/heads/main'
    needs:
      - lint
      - test
    env:
      VERCEL_PROJECT_ID: prj_PBGTsidF0cEZ6uj5mN2Rev0pulxG
    steps:
      - uses: actions/checkout@v3
      - uses: aboutbits/github-actions-node/setup-and-install@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - uses: aboutbits/github-actions-vercel/deploy@v1
        with:
          arguments: --prod

  deploy-next:
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true
    if: github.ref == 'refs/heads/next'
    needs:
      - lint
      - test
    env:
      VERCEL_PROJECT_ID: prj_LzxUR2ScPhpdn1e9JCwTSNXLoNFH
    steps:
      - uses: actions/checkout@v3
      - uses: aboutbits/github-actions-node/setup-and-install@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - uses: aboutbits/github-actions-vercel/deploy@v1
        with:
          arguments: --prod
