name: Main

on:
  push:
    branches:
      - main

env:
  NODE_VERSION: 20

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  checks:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    strategy:
      matrix:
        node_version: [16, 18, 20]
    steps:
      - uses: actions/checkout@v4
      - uses: aboutbits/github-actions-node/setup-and-install@v2
        with:
          node-version: ${{ matrix.node_version }}
      - name: Lint
        run: npm run lint
        shell: bash
      - name: Typecheck
        run: npm run typecheck
        shell: bash

  test:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    strategy:
      matrix:
        node_version: [16, 18, 20]
    steps:
      - uses: actions/checkout@v4
      - uses: aboutbits/github-actions-node/setup-and-install@v2
        with:
          node-version: ${{ matrix.node_version }}
      - name: Test
        run: npm run test
        shell: bash

  deploy-main:
    runs-on: ubuntu-22.04
    timeout-minutes: 20
    if: github.ref == 'refs/heads/main'
    needs:
      - checks
      - test
    steps:
      - uses: actions/checkout@v4
      - uses: aboutbits/github-actions-node/setup-and-install@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - uses: aboutbits/github-actions-vercel/deploy@v1
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-organization-id: team_e2WfHoRuw9BQVW7oYmMSKRJ6
          vercel-project-id: prj_PBGTsidF0cEZ6uj5mN2Rev0pulxG
          build-arguments: --prod
          deploy-arguments: --prod
