name: Preview

on:
  workflow_run:
    workflows: [Main]
    types: [completed]
  pull_request:
    types: [opened, reopened, synchronize]

env:
  NODE_VERSION: 16
  PREVIEW_DOMAIN: react-ui.aboutbits.dev

jobs:
  create-link:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    if: ${{ github.event.pull_request.action == 'opened' }}
    steps:
      - uses: actions/checkout@v3
      - uses: aboutbits/github-actions-node/setup@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - uses: aboutbits/github-actions-vercel/add-domain@v1
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-scope: aboutbits
          vercel-organization-id: team_e2WfHoRuw9BQVW7oYmMSKRJ6
          vercel-project-id: prj_LzxUR2ScPhpdn1e9JCwTSNXLoNFH
          domain: ${{ github.event.pull_request.number }}.${{ env.PREVIEW_DOMAIN }}
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '[https://${{ github.event.pull_request.number }}.${{ env.PREVIEW_DOMAIN }}](https://${{ github.event.pull_request.number }}.${{ env.PREVIEW_DOMAIN }})'
            })

  deploy-preview:
    runs-on: ubuntu-22.04
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v3
      - uses: aboutbits/github-actions-node/setup-and-install@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - id: deploy
        uses: aboutbits/github-actions-vercel/deploy@v1
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-scope: aboutbits
          vercel-organization-id: team_e2WfHoRuw9BQVW7oYmMSKRJ6
          vercel-project-id: prj_LzxUR2ScPhpdn1e9JCwTSNXLoNFH
      - uses: aboutbits/github-actions-vercel/link-domain@v1
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-scope: aboutbits
          vercel-organization-id: team_e2WfHoRuw9BQVW7oYmMSKRJ6
          vercel-project-id: prj_LzxUR2ScPhpdn1e9JCwTSNXLoNFH
          domain: ${{ github.event.pull_request.number }}.${{ env.PREVIEW_DOMAIN }}
          url: ${{ steps.deploy.outputs.url }}
